export const VEG_DATA = [
    {
        "vegName": "Beans - Green",
        "variety": "Kentucky Blue",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 26,
        "packSize": 1,
        "unit": "1lb bag",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1012182
    },
    {
        "vegName": "Beets",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 16,
        "ReadyWeek": 23,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1021868
    },
    {
        "vegName": "Beets",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 19,
        "ReadyWeek": 26,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1022285
    },
    {
        "vegName": "Broccoli",
        "variety": "Gypsy",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 16,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 104075
    },
    {
        "vegName": "Broccoli",
        "variety": "Gypsy",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 20,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 104714
    },
    {
        "vegName": "Broccoli",
        "variety": "Gypsy",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 24,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1031235
    },
    {
        "vegName": "Broccoli",
        "variety": "Gypsy",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 28,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1032017
    },
    {
        "vegName": "Broccoli",
        "variety": "Gypsy",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 32,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1032215
    },
    {
        "vegName": "Broccoli",
        "variety": "Imperial",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 18,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 104313
    },
    {
        "vegName": "Broccoli",
        "variety": "Imperial",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 22,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 104219
    },
    {
        "vegName": "Broccoli",
        "variety": "Imperial",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 26,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1031914
    },
    {
        "vegName": "Broccoli",
        "variety": "Imperial",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 30,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1031670
    },
    {
        "vegName": "Broccoli",
        "variety": "Imperial",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 34,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1032862
    },
    {
        "vegName": "Broccoli",
        "variety": "Millennium",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 18,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 104208
    },
    {
        "vegName": "Broccoli",
        "variety": "Millennium",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 22,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 104605
    },
    {
        "vegName": "Broccoli",
        "variety": "Millennium",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 26,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1031388
    },
    {
        "vegName": "Broccoli",
        "variety": "Millennium",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 30,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1032405
    },
    {
        "vegName": "Broccoli",
        "variety": "Millennium",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 34,
        "packSize": 1,
        "unit": "Bag",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1032868
    },
    {
        "vegName": "Brussel Sprouts",
        "variety": "Franklin",
        "cropNum": 1,
        "plantWeek": 10,
        "ReadyWeek": 32,
        "packSize": 1,
        "unit": "Stalk",
        "credits": 3,
        "sold": 0,
        "status": "Not Available",
        "key": 1042008
    },
    {
        "vegName": "Brussel Sprouts",
        "variety": "Dagan",
        "cropNum": 1,
        "plantWeek": 10,
        "ReadyWeek": 29,
        "packSize": 1,
        "unit": "Stalk",
        "credits": 3,
        "sold": 0,
        "status": "Not Available",
        "key": 1041605
    },
    {
        "vegName": "Cabbage - Chinese",
        "variety": "Minuet",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 14,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Coming Soon",
        "key": 105535
    },
    {
        "vegName": "Cabbage - Chinese",
        "variety": "Minuet",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 18,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Coming Soon",
        "key": 106533
    },
    {
        "vegName": "Cabbage - Chinese",
        "variety": "Minuet",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 22,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1051701
    },
    {
        "vegName": "Cabbage - Chinese",
        "variety": "Minuet",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 26,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1051586
    },
    {
        "vegName": "Cabbage - Chinese",
        "variety": "Minuet",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 30,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1052678
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Tiara",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 16,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 107005
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Tiara",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 20,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 107507
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Tiara",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 24,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1061737
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Tiara",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 28,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1061670
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Tiara",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 32,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1062423
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Fresh Market",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 18,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 106520
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Fresh Market",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 22,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 106932
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Fresh Market",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 26,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1061238
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Fresh Market",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 30,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1062459
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Fresh Market",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 34,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1062912
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Earliana",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 16,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 106570
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Earliana",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 20,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 107131
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Earliana",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 24,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1061128
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Earliana",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 28,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1062491
    },
    {
        "vegName": "Cabbage - Green",
        "variety": "Earliana",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 32,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1062200
    },
    {
        "vegName": "Cabbage - Purple",
        "variety": "Omero",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 18,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 107902
    },
    {
        "vegName": "Cabbage - Purple",
        "variety": "Omero",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 22,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 108650
    },
    {
        "vegName": "Cabbage - Purple",
        "variety": "Omero",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 26,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1071285
    },
    {
        "vegName": "Cabbage - Purple",
        "variety": "Ruby Ball",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 19,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 108269
    },
    {
        "vegName": "Cabbage - Purple",
        "variety": "Ruby Ball",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 23,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 107889
    },
    {
        "vegName": "Cabbage - Purple",
        "variety": "Ruby Ball",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 27,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1071307
    },
    {
        "vegName": "Cabbage - Purple",
        "variety": "Ruby Ball",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 31,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1071736
    },
    {
        "vegName": "Carrots",
        "variety": "Bolero",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 24,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1081599
    },
    {
        "vegName": "Carrots",
        "variety": "Bolero",
        "cropNum": 2,
        "plantWeek": 17,
        "ReadyWeek": 28,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1081881
    },
    {
        "vegName": "Carrots",
        "variety": "Bolero",
        "cropNum": 3,
        "plantWeek": 21,
        "ReadyWeek": 32,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1082545
    },
    {
        "vegName": "Carrots",
        "variety": "Yaya",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 22,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1081789
    },
    {
        "vegName": "Carrots",
        "variety": "Yaya",
        "cropNum": 2,
        "plantWeek": 17,
        "ReadyWeek": 26,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1082275
    },
    {
        "vegName": "Carrots",
        "variety": "Yaya",
        "cropNum": 3,
        "plantWeek": 21,
        "ReadyWeek": 30,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1082726
    },
    {
        "vegName": "Carrots",
        "variety": "Napoli",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 21,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1081824
    },
    {
        "vegName": "Carrots",
        "variety": "Napoli",
        "cropNum": 2,
        "plantWeek": 17,
        "ReadyWeek": 25,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1082211
    },
    {
        "vegName": "Carrots",
        "variety": "Napoli",
        "cropNum": 3,
        "plantWeek": 21,
        "ReadyWeek": 29,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1082855
    },
    {
        "vegName": "Carrots",
        "variety": "Naval",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 24,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1081997
    },
    {
        "vegName": "Carrots",
        "variety": "Naval",
        "cropNum": 2,
        "plantWeek": 17,
        "ReadyWeek": 28,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1081905
    },
    {
        "vegName": "Carrots",
        "variety": "Naval",
        "cropNum": 3,
        "plantWeek": 21,
        "ReadyWeek": 32,
        "packSize": 6,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1082914
    },
    {
        "vegName": "Cauliflower",
        "variety": "Bishop",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 17,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 110238
    },
    {
        "vegName": "Cauliflower",
        "variety": "Bishop",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 21,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 110648
    },
    {
        "vegName": "Cauliflower",
        "variety": "Bishop",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 25,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1091299
    },
    {
        "vegName": "Cauliflower",
        "variety": "Bishop",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 29,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092267
    },
    {
        "vegName": "Cauliflower",
        "variety": "Bishop",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 33,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092528
    },
    {
        "vegName": "Cauliflower",
        "variety": "Denali",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 18,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 110082
    },
    {
        "vegName": "Cauliflower",
        "variety": "Denali",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 22,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 110631
    },
    {
        "vegName": "Cauliflower",
        "variety": "Denali",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 26,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1091920
    },
    {
        "vegName": "Cauliflower",
        "variety": "Denali",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 30,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092500
    },
    {
        "vegName": "Cauliflower",
        "variety": "Denali",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 34,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092387
    },
    {
        "vegName": "Cauliflower",
        "variety": "Snow Crown",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 14,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 109450
    },
    {
        "vegName": "Cauliflower",
        "variety": "Snow Crown",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 18,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 109820
    },
    {
        "vegName": "Cauliflower",
        "variety": "Snow Crown",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 22,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1091309
    },
    {
        "vegName": "Cauliflower",
        "variety": "Snow Crown",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 26,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1091898
    },
    {
        "vegName": "Cauliflower",
        "variety": "Snow Crown",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 30,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092239
    },
    {
        "vegName": "Cauliflower",
        "variety": "Candid Charm",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 17,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 109384
    },
    {
        "vegName": "Cauliflower",
        "variety": "Candid Charm",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 21,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 110559
    },
    {
        "vegName": "Cauliflower",
        "variety": "Candid Charm",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 25,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092025
    },
    {
        "vegName": "Cauliflower",
        "variety": "Candid Charm",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 29,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092289
    },
    {
        "vegName": "Cauliflower",
        "variety": "Candid Charm",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 33,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092586
    },
    {
        "vegName": "Cauliflower",
        "variety": "Amazing",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 17,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 110031
    },
    {
        "vegName": "Cauliflower",
        "variety": "Amazing",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 21,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 110719
    },
    {
        "vegName": "Cauliflower",
        "variety": "Amazing",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 25,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1091857
    },
    {
        "vegName": "Cauliflower",
        "variety": "Amazing",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 29,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092061
    },
    {
        "vegName": "Cauliflower",
        "variety": "Amazing",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 33,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1092777
    },
    {
        "vegName": "Cauliflower - Specialty",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 17,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 110787
    },
    {
        "vegName": "Cauliflower - Specialty",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 21,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 111514
    },
    {
        "vegName": "Cauliflower - Specialty",
        "variety": "",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 25,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1101167
    },
    {
        "vegName": "Cauliflower - Specialty",
        "variety": "",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 29,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1102312
    },
    {
        "vegName": "Cauliflower - Specialty",
        "variety": "",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 33,
        "packSize": 1,
        "unit": "Full Head",
        "credits": 4,
        "sold": 0,
        "status": "Not Available",
        "key": 1102170
    },
    {
        "vegName": "Celery",
        "variety": "Tango",
        "cropNum": 1,
        "plantWeek": 6,
        "ReadyWeek": 22,
        "packSize": 1,
        "unit": "Head",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 111839
    },
    {
        "vegName": "Corn - Ornamental",
        "variety": "Painted Mountain",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 30,
        "packSize": 2,
        "unit": "Ears",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1132271
    },
    {
        "vegName": "Corn - Sweet",
        "variety": "Trinity",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 28,
        "packSize": 3,
        "unit": "Ears",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1122764
    },
    {
        "vegName": "Corn - Sweet",
        "variety": "Trinity",
        "cropNum": 2,
        "plantWeek": 22,
        "ReadyWeek": 32,
        "packSize": 3,
        "unit": "Ears",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1122702
    },
    {
        "vegName": "Corn - Sweet",
        "variety": "Sugar Buns",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 28,
        "packSize": 3,
        "unit": "Ears",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1122638
    },
    {
        "vegName": "Corn - Sweet",
        "variety": "Sugar Buns",
        "cropNum": 2,
        "plantWeek": 22,
        "ReadyWeek": 32,
        "packSize": 3,
        "unit": "Ears",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1122402
    },
    {
        "vegName": "Corn - Sweet",
        "variety": "Delectable",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 30,
        "packSize": 3,
        "unit": "Ears",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1122678
    },
    {
        "vegName": "Corn - Sweet",
        "variety": "Delectable",
        "cropNum": 2,
        "plantWeek": 22,
        "ReadyWeek": 34,
        "packSize": 3,
        "unit": "Ears",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1122800
    },
    {
        "vegName": "Corn - Sweet",
        "variety": "Bodacious",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 31,
        "packSize": 3,
        "unit": "Ears",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1122583
    },
    {
        "vegName": "Corn - Sweet",
        "variety": "Bodacious",
        "cropNum": 2,
        "plantWeek": 22,
        "ReadyWeek": 35,
        "packSize": 3,
        "unit": "Ears",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1122303
    },
    {
        "vegName": "Cucumber - Pickler",
        "variety": "Excelsior",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 23,
        "packSize": 3,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1142206
    },
    {
        "vegName": "Cucumber - Pickler",
        "variety": "Regal",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 23,
        "packSize": 3,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1141824
    },
    {
        "vegName": "Cucumber - Slicer",
        "variety": "Summer Dance",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 25,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1151918
    },
    {
        "vegName": "Cucumber - Slicer",
        "variety": "Itachi",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 23,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1151420
    },
    {
        "vegName": "Cucumber - Slicer",
        "variety": "Armenian",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 25,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1151443
    },
    {
        "vegName": "Eggplant",
        "variety": "Nadia",
        "cropNum": 1,
        "plantWeek": 11,
        "ReadyWeek": 25,
        "packSize": 1,
        "unit": "Each",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1161482
    },
    {
        "vegName": "Garden Bouquet",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 0,
        "ReadyWeek": 0,
        "packSize": 1,
        "unit": "Bouquet",
        "credits": 3,
        "sold": 40,
        "status": "Not Available",
        "key": 12209
    },
    {
        "vegName": "Gourd - Large",
        "variety": "Beetlejuice",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 33,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1181745
    },
    {
        "vegName": "Gourd - Large",
        "variety": "Autumn Wings",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 31,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1182422
    },
    {
        "vegName": "Gourd - Small",
        "variety": "Daisy Mix",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 30,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1191997
    },
    {
        "vegName": "Gourd - Small",
        "variety": "Batwing Mix",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 30,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1192517
    },
    {
        "vegName": "Gourd - Small",
        "variety": "Superfreak Gremlins",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 31,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1192030
    },
    {
        "vegName": "Herb - Basil",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 12594
    },
    {
        "vegName": "Herb - Basil",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 7,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 12358
    },
    {
        "vegName": "Herb - Chives",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 0,
        "ReadyWeek": 0,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 9,
        "status": "Available",
        "key": 12751
    },
    {
        "vegName": "Herb - Cilantro",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 13036
    },
    {
        "vegName": "Herb - Cilantro",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 6,
        "ReadyWeek": 6,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 12771
    },
    {
        "vegName": "Herb - Cilantro",
        "variety": "",
        "cropNum": 3,
        "plantWeek": 9,
        "ReadyWeek": 9,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 13235
    },
    {
        "vegName": "Herb - Cilantro",
        "variety": "",
        "cropNum": 4,
        "plantWeek": 12,
        "ReadyWeek": 12,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1231919
    },
    {
        "vegName": "Herb - Cilantro",
        "variety": "",
        "cropNum": 5,
        "plantWeek": 15,
        "ReadyWeek": 15,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1231961
    },
    {
        "vegName": "Herb - Lavender",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 13068
    },
    {
        "vegName": "Herb - Mint",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 0,
        "ReadyWeek": 0,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 13223
    },
    {
        "vegName": "Herb - Oregano",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 13363
    },
    {
        "vegName": "Herb - Parsley",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 12858
    },
    {
        "vegName": "Herb - Parsley",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 12878
    },
    {
        "vegName": "Herb - Rosemary",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 13791
    },
    {
        "vegName": "Herb - Sage",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 13727
    },
    {
        "vegName": "Herb - Thyme",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 13476
    },
    {
        "vegName": "Kale",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 13995
    },
    {
        "vegName": "Kale",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 8,
        "ReadyWeek": 8,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 13730
    },
    {
        "vegName": "Kohlrabi",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 13277
    },
    {
        "vegName": "Kohlrabi",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 7,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 14172
    },
    {
        "vegName": "Kohlrabi",
        "variety": "",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 11,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1321915
    },
    {
        "vegName": "Kohlrabi",
        "variety": "",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 15,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1322319
    },
    {
        "vegName": "Kohlrabi",
        "variety": "",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 19,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1322534
    },
    {
        "vegName": "Leeks",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 18,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1332476
    },
    {
        "vegName": "Lettuce - Romaine",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 3,
        "status": "Available",
        "key": 14598
    },
    {
        "vegName": "Lettuce - Romaine",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 7,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 3,
        "status": "Available",
        "key": 14167
    },
    {
        "vegName": "Lettuce - Romaine",
        "variety": "",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 11,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 3,
        "status": "Available",
        "key": 1371221
    },
    {
        "vegName": "Lettuce - Romaine",
        "variety": "",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 15,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 3,
        "status": "Available",
        "key": 1371659
    },
    {
        "vegName": "Lettuce - Romaine",
        "variety": "",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 19,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 3,
        "status": "Available",
        "key": 1372047
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 14460
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 7,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 13675
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 11,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 1351488
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 15,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 1352409
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 19,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 1352786
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 13972
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 7,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 13662
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 11,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 1351871
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 15,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 1352513
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Green",
        "variety": "",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 19,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 1352488
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Red",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 3,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 14603
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Red",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 7,
        "ReadyWeek": 7,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 14416
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Red",
        "variety": "",
        "cropNum": 3,
        "plantWeek": 11,
        "ReadyWeek": 11,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 1361256
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Red",
        "variety": "",
        "cropNum": 4,
        "plantWeek": 15,
        "ReadyWeek": 15,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 1362431
    },
    {
        "vegName": "Lettuce - Sweet Crisp - Red",
        "variety": "",
        "cropNum": 5,
        "plantWeek": 19,
        "ReadyWeek": 19,
        "packSize": 1,
        "unit": "Head",
        "credits": 3,
        "sold": 6,
        "status": "Available",
        "key": 1362664
    },
    {
        "vegName": "Melon - Canteloupe",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 17,
        "packSize": 1,
        "unit": "Each",
        "credits": 3,
        "sold": 0,
        "status": "Not Available",
        "key": 1382018
    },
    {
        "vegName": "Melon - Honey Dew",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 17,
        "packSize": 1,
        "unit": "Each",
        "credits": 3,
        "sold": 0,
        "status": "Not Available",
        "key": 1391816
    },
    {
        "vegName": "Melon - Muskmelon",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 17,
        "packSize": 1,
        "unit": "Each",
        "credits": 3,
        "sold": 0,
        "status": "Not Available",
        "key": 1401750
    },
    {
        "vegName": "Melon - Watermelon",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 17,
        "packSize": 1,
        "unit": "Each",
        "credits": 3,
        "sold": 0,
        "status": "Not Available",
        "key": 1412602
    },
    {
        "vegName": "Onion - Bulb - Red",
        "variety": "Red Zeppelin",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 32,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1422369
    },
    {
        "vegName": "Onion - Bulb - Red",
        "variety": "Red Wing",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 35,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1421967
    },
    {
        "vegName": "Onion - Bulb - Yellow",
        "variety": "Patterson",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 32,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1432567
    },
    {
        "vegName": "Onion - Bulb - Yellow",
        "variety": "Ailsa Craig",
        "cropNum": 1,
        "plantWeek": 18,
        "ReadyWeek": 31,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1432036
    },
    {
        "vegName": "Onion - Green",
        "variety": "Guardsman",
        "cropNum": 1,
        "plantWeek": 3,
        "ReadyWeek": 10,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 144921
    },
    {
        "vegName": "Onion - Green",
        "variety": "Guardsman",
        "cropNum": 2,
        "plantWeek": 6,
        "ReadyWeek": 13,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 144704
    },
    {
        "vegName": "Onion - Green",
        "variety": "Guardsman",
        "cropNum": 3,
        "plantWeek": 9,
        "ReadyWeek": 16,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 145576
    },
    {
        "vegName": "Peas - Snap",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 13,
        "ReadyWeek": 13,
        "packSize": 1,
        "unit": "Lb",
        "credits": 2,
        "sold": 0,
        "status": "Coming Soon",
        "key": 1451855
    },
    {
        "vegName": "Pepper - Bell - Colored",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 10,
        "ReadyWeek": 10,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1461614
    },
    {
        "vegName": "Pepper - Bell - Green",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 10,
        "ReadyWeek": 10,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1471899
    },
    {
        "vegName": "Pepper - Hot",
        "variety": "Jalepeno",
        "cropNum": 1,
        "plantWeek": 8,
        "ReadyWeek": 8,
        "packSize": 3,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 15230
    },
    {
        "vegName": "Plum - Purple",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 0,
        "ReadyWeek": 0,
        "packSize": 1,
        "unit": "Lb",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 15045
    },
    {
        "vegName": "Plum - Yellow",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 0,
        "ReadyWeek": 0,
        "packSize": 1,
        "unit": "Lb",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 15316
    },
    {
        "vegName": "Pumpkin - Baking",
        "variety": "Winter Luxury",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 30,
        "packSize": 2,
        "unit": "Lbs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1512710
    },
    {
        "vegName": "Pumpkin - Baking",
        "variety": "Gum Drop",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 31,
        "packSize": 2,
        "unit": "Lbs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1512431
    },
    {
        "vegName": "Pumpkin - Cotton Candy",
        "variety": "Cotton Candy",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 32,
        "packSize": 2,
        "unit": "Lbs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1531972
    },
    {
        "vegName": "Pumpkin - Jack O'Lantern",
        "variety": "Atlantic Giant",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 34,
        "packSize": 2,
        "unit": "Lbs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1522067
    },
    {
        "vegName": "Pumpkin - Jack O'Lantern",
        "variety": "Renegade",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 32,
        "packSize": 2,
        "unit": "Lbs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1521910
    },
    {
        "vegName": "Pumpkin - Jack O'Lantern",
        "variety": "Early Giant",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 30,
        "packSize": 2,
        "unit": "Lbs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1521963
    },
    {
        "vegName": "Pumpkin - Mini",
        "variety": "Harvest Blend",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 31,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1542135
    },
    {
        "vegName": "Pumpkin - Warty",
        "variety": "Knucklehead",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 32,
        "packSize": 2,
        "unit": "Lbs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1552003
    },
    {
        "vegName": "Radish",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 16,
        "ReadyWeek": 16,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 1,
        "sold": 0,
        "status": "Available",
        "key": 1562152
    },
    {
        "vegName": "Raspberry",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 0,
        "ReadyWeek": 0,
        "packSize": 1,
        "unit": "Pint",
        "credits": 3,
        "sold": 0,
        "status": "Not Available",
        "key": 16088
    },
    {
        "vegName": "Rhubarb",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 0,
        "ReadyWeek": 0,
        "packSize": 4,
        "unit": "Stalks ",
        "credits": 3,
        "sold": 0,
        "status": "Available",
        "key": 16231
    },
    {
        "vegName": "Spinach",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 16,
        "ReadyWeek": 16,
        "packSize": 1,
        "unit": "Bag",
        "credits": 2,
        "sold": 0,
        "status": "Available",
        "key": 1592406
    },
    {
        "vegName": "Spinach",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 20,
        "ReadyWeek": 20,
        "packSize": 1,
        "unit": "Bag",
        "credits": 2,
        "sold": 0,
        "status": "Available",
        "key": 1592105
    },
    {
        "vegName": "Squash - Butternut",
        "variety": "Butterscotch",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 31,
        "packSize": 1,
        "unit": "Each",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1602508
    },
    {
        "vegName": "Squash - Hubbard",
        "variety": "Sweet Meat",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 34,
        "packSize": 2,
        "unit": "Lbs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1612392
    },
    {
        "vegName": "Squash - Large Zucchini",
        "variety": "Cash Machine",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 25,
        "packSize": 1,
        "unit": "Each",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1622489
    },
    {
        "vegName": "Squash - Small Zucchini",
        "variety": "Yellowfin",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 24,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1631937
    },
    {
        "vegName": "Squash - Spaghetti",
        "variety": "Spaghetti Winter",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 30,
        "packSize": 1,
        "unit": "Each",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1642471
    },
    {
        "vegName": "Swiss Chard",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 12,
        "ReadyWeek": 12,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 2,
        "sold": 0,
        "status": "Available",
        "key": 1651798
    },
    {
        "vegName": "Swiss Chard",
        "variety": "",
        "cropNum": 2,
        "plantWeek": 16,
        "ReadyWeek": 16,
        "packSize": 1,
        "unit": "Bunch",
        "credits": 2,
        "sold": 0,
        "status": "Available",
        "key": 1651660
    },
    {
        "vegName": "Tomato - Cherry",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 11,
        "ReadyWeek": 11,
        "packSize": 1,
        "unit": "Lb",
        "credits": 2,
        "sold": 0,
        "status": "Not Available",
        "key": 1661462
    },
    {
        "vegName": "Tomato - Green",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 17,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1202218
    },
    {
        "vegName": "Tomato - Paste",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 11,
        "ReadyWeek": 11,
        "packSize": 3,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1671399
    },
    {
        "vegName": "Tomato - Slicer",
        "variety": "",
        "cropNum": 1,
        "plantWeek": 11,
        "ReadyWeek": 11,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1681560
    },
    {
        "vegName": "Tomato - Slicer",
        "variety": "Heirloom",
        "cropNum": 1,
        "plantWeek": 17,
        "ReadyWeek": 17,
        "packSize": 2,
        "unit": "Pcs",
        "credits": 1,
        "sold": 0,
        "status": "Not Available",
        "key": 1682299
    }
]